# Generated by Django 4.0.4 on 2022-05-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_institution_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['type']},
        ),
    ]
